import os


TWO_WEEKS = 1209600
TOKEN_EXPIRES = TWO_WEEKS

SECRET_KEY = os.getenv('SECRET_KEY')
assert SECRET_KEY

AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID')
assert AWS_ACCESS_KEY_ID

AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY')
assert AWS_SECRET_ACCESS_KEY
